management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true
