server:
  port: 8080


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "*" ]
  endpoint:
    prometheus:
      enabled: true
    export:
      prometheus:
        enabled: true