version: "3.8"
services:
  pubsub-emulator:
    container_name: pubsub
    image: google/cloud-sdk:emulators
    ports:
      - "8085:8085"  # Maps emulator port (8085) to host port (8085)
    command: |
      gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=example
