# Another way of configuring the cache




spring:
  cache:
    cache-names: "BASIC_CACHE_NAME"
    caffeine:
      spec: "maximumSize=10000,expireAfterWrite=5s"





management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true