# Another way of configuring the cache
#spring:
#  cache:
#    cache-names: "randomResponse"
#    caffeine:
#      spec: "maximumSize=500,expireAfterWrite=5s"

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true